/**
 * Curated dataset for the font-picker lab entry (`/lab/pick-a-font`).
 *
 * Axis values (tone / era / voice / warmth) are curatorial judgments, not
 * measurements — see CONTEXT.md's "Font picker" glossary for what each axis
 * means and how a "match" / "stretch" is chosen from them.
 *
 * `css` URLs are believed correct at time of writing but are verified by a
 * separate script, not by this file.
 */

export type FontRole = 'display' | 'body' | 'mono';
export type FontSource = 'google' | 'fontshare' | 'independent';

export interface FontAxes {
  /** 0 = serious, 1 = playful */
  tone: number;
  /** 0 = timeless, 1 = current */
  era: number;
  /** 0 = quiet (disappears), 1 = loud (performs) */
  voice: number;
  /** 0 = precise (compass-drawn), 1 = warm (hand-drawn) */
  warmth: number;
}

export interface PickerFont {
  /** Exact CSS font-family name as served by its stylesheet */
  family: string;
  role: FontRole;
  axes: FontAxes;
  source: FontSource;
  /** Human license label, e.g. 'OFL', 'ITF FFL', 'Apache 2.0' */
  license: string;
  /** Link out to the font's home page */
  url: string;
  /** Stylesheet URL(s) that load the family (400 + 700 where available) */
  css: string[];
  /** Cross-role companion families — must name other fonts in THIS dataset */
  companions: string[];
}

export const PICKER_FONTS: PickerFont[] = [
  // ---------------------------------------------------------------------
  // display
  // ---------------------------------------------------------------------
  {
    family: 'Anton',
    role: 'display',
    axes: { tone: 0.35, era: 0.55, voice: 0.9, warmth: 0.1 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Anton',
    css: ['https://fonts.googleapis.com/css2?family=Anton&display=swap'],
    companions: ['Inter', 'Work Sans'],
  },
  {
    family: 'Archivo',
    role: 'display',
    axes: { tone: 0.25, era: 0.7, voice: 0.55, warmth: 0.15 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Archivo',
    css: ['https://fonts.googleapis.com/css2?family=Archivo:wght@400;700&display=swap'],
    companions: ['Inter', 'Source Sans 3'],
  },
  {
    family: 'Bricolage Grotesque',
    role: 'display',
    axes: { tone: 0.4, era: 0.85, voice: 0.6, warmth: 0.35 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Bricolage+Grotesque',
    css: ['https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:wght@400;700&display=swap'],
    companions: ['Inter', 'Work Sans'],
  },
  {
    family: 'Caveat',
    role: 'display',
    axes: { tone: 0.85, era: 0.35, voice: 0.45, warmth: 0.95 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Caveat',
    css: ['https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&display=swap'],
    companions: ['Source Sans 3', 'Lora'],
  },
  {
    family: 'Clash Display',
    role: 'display',
    axes: { tone: 0.3, era: 0.9, voice: 0.65, warmth: 0.1 },
    source: 'fontshare',
    license: 'ITF FFL',
    url: 'https://www.fontshare.com/fonts/clash-display',
    css: ['https://api.fontshare.com/v2/css?f[]=clash-display@400,700&display=swap'],
    companions: ['Satoshi', 'General Sans'],
  },
  {
    family: 'Cooper Hewitt',
    role: 'display',
    axes: { tone: 0.3, era: 0.5, voice: 0.4, warmth: 0.3 },
    source: 'independent',
    license: 'OFL',
    url: 'https://fontsource.org/fonts/cooper-hewitt',
    css: ['https://cdn.jsdelivr.net/fontsource/css/cooper-hewitt@latest/index.css'],
    companions: ['Inter'],
  },
  {
    family: 'Cormorant Garamond',
    role: 'display',
    axes: { tone: 0.3, era: 0.1, voice: 0.35, warmth: 0.6 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Cormorant+Garamond',
    css: ['https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@400;700&display=swap'],
    companions: ['Source Sans 3', 'Work Sans'],
  },
  {
    family: 'DM Serif Display',
    role: 'display',
    axes: { tone: 0.3, era: 0.4, voice: 0.55, warmth: 0.4 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/DM+Serif+Display',
    css: ['https://fonts.googleapis.com/css2?family=DM+Serif+Display&display=swap'],
    companions: ['DM Sans', 'Inter'],
  },
  {
    family: 'EB Garamond',
    role: 'display',
    axes: { tone: 0.15, era: 0.05, voice: 0.25, warmth: 0.5 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/EB+Garamond',
    css: ['https://fonts.googleapis.com/css2?family=EB+Garamond:wght@400;700&display=swap'],
    companions: ['Source Sans 3', 'Work Sans'],
  },
  {
    family: 'Fraunces',
    role: 'display',
    axes: { tone: 0.65, era: 0.4, voice: 0.5, warmth: 0.55 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Fraunces',
    css: ['https://fonts.googleapis.com/css2?family=Fraunces:wght@400;700&display=swap'],
    companions: ['Inter', 'Work Sans'],
  },
  {
    family: 'Fredoka',
    role: 'display',
    axes: { tone: 0.9, era: 0.6, voice: 0.55, warmth: 0.6 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Fredoka',
    css: ['https://fonts.googleapis.com/css2?family=Fredoka:wght@400;700&display=swap'],
    companions: ['Nunito Sans', 'Work Sans'],
  },
  {
    family: 'Instrument Serif',
    role: 'display',
    axes: { tone: 0.4, era: 0.3, voice: 0.45, warmth: 0.5 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Instrument+Serif',
    css: ['https://fonts.googleapis.com/css2?family=Instrument+Serif&display=swap'],
    companions: ['Inter', 'General Sans'],
  },
  {
    family: 'Jost',
    role: 'display',
    axes: { tone: 0.2, era: 0.55, voice: 0.3, warmth: 0.05 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Jost',
    css: ['https://fonts.googleapis.com/css2?family=Jost:wght@400;700&display=swap'],
    companions: ['Inter', 'Source Sans 3'],
  },
  {
    family: 'Libre Caslon Display',
    role: 'display',
    axes: { tone: 0.2, era: 0.2, voice: 0.5, warmth: 0.35 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Libre+Caslon+Display',
    css: ['https://fonts.googleapis.com/css2?family=Libre+Caslon+Display&display=swap'],
    companions: ['Source Sans 3', 'Work Sans'],
  },
  {
    family: 'Lobster',
    role: 'display',
    axes: { tone: 0.75, era: 0.35, voice: 0.7, warmth: 0.65 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Lobster',
    css: ['https://fonts.googleapis.com/css2?family=Lobster&display=swap'],
    companions: ['Nunito Sans', 'Inter'],
  },
  {
    family: 'Manrope',
    role: 'display',
    axes: { tone: 0.3, era: 0.75, voice: 0.35, warmth: 0.15 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Manrope',
    css: ['https://fonts.googleapis.com/css2?family=Manrope:wght@400;700&display=swap'],
    companions: ['Inter', 'Source Sans 3'],
  },
  {
    family: 'Outfit',
    role: 'display',
    axes: { tone: 0.35, era: 0.8, voice: 0.4, warmth: 0.15 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Outfit',
    css: ['https://fonts.googleapis.com/css2?family=Outfit:wght@400;700&display=swap'],
    companions: ['Inter', 'Work Sans'],
  },
  {
    family: 'Playfair Display',
    role: 'display',
    axes: { tone: 0.3, era: 0.3, voice: 0.6, warmth: 0.4 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Playfair+Display',
    css: ['https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;700&display=swap'],
    companions: ['Source Sans 3', 'Work Sans'],
  },
  {
    family: 'Poppins',
    role: 'display',
    axes: { tone: 0.5, era: 0.65, voice: 0.45, warmth: 0.3 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Poppins',
    css: ['https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap'],
    companions: ['Inter', 'Nunito Sans'],
  },
  {
    family: 'Bebas Neue',
    role: 'display',
    axes: { tone: 0.4, era: 0.6, voice: 0.85, warmth: 0.1 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Bebas+Neue',
    css: ['https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap'],
    companions: ['Inter', 'Work Sans'],
  },
  {
    family: 'Sentient',
    role: 'display',
    axes: { tone: 0.35, era: 0.35, voice: 0.4, warmth: 0.55 },
    source: 'fontshare',
    license: 'ITF FFL',
    url: 'https://www.fontshare.com/fonts/sentient',
    css: ['https://api.fontshare.com/v2/css?f[]=sentient@400,700&display=swap'],
    companions: ['General Sans', 'Satoshi'],
  },
  {
    family: 'Space Grotesk',
    role: 'display',
    axes: { tone: 0.35, era: 0.85, voice: 0.5, warmth: 0.25 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Space+Grotesk',
    css: ['https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;700&display=swap'],
    companions: ['Inter', 'Work Sans'],
  },
  {
    family: 'Unbounded',
    role: 'display',
    axes: { tone: 0.6, era: 0.95, voice: 0.75, warmth: 0.25 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Unbounded',
    css: ['https://fonts.googleapis.com/css2?family=Unbounded:wght@400;700&display=swap'],
    companions: ['Inter', 'General Sans'],
  },
  {
    family: 'Young Serif',
    role: 'display',
    axes: { tone: 0.55, era: 0.3, voice: 0.4, warmth: 0.5 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Young+Serif',
    css: ['https://fonts.googleapis.com/css2?family=Young+Serif&display=swap'],
    companions: ['Inter', 'Work Sans'],
  },
  {
    family: 'Zodiak',
    role: 'display',
    axes: { tone: 0.4, era: 0.35, voice: 0.55, warmth: 0.45 },
    source: 'fontshare',
    license: 'ITF FFL',
    url: 'https://www.fontshare.com/fonts/zodiak',
    css: ['https://api.fontshare.com/v2/css?f[]=zodiak@400,700&display=swap'],
    companions: ['General Sans', 'Satoshi'],
  },

  // ---------------------------------------------------------------------
  // body
  // ---------------------------------------------------------------------
  {
    family: 'Atkinson Hyperlegible',
    role: 'body',
    axes: { tone: 0.15, era: 0.5, voice: 0.15, warmth: 0.3 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Atkinson+Hyperlegible',
    css: ['https://fonts.googleapis.com/css2?family=Atkinson+Hyperlegible:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Archivo', 'Space Grotesk'],
  },
  {
    family: 'Cabinet Grotesk',
    role: 'body',
    axes: { tone: 0.35, era: 0.75, voice: 0.25, warmth: 0.2 },
    source: 'fontshare',
    license: 'ITF FFL',
    url: 'https://www.fontshare.com/fonts/cabinet-grotesk',
    css: ['https://api.fontshare.com/v2/css?f[]=cabinet-grotesk@400,700&display=swap'],
    companions: ['Clash Display', 'Unbounded'],
  },
  {
    family: 'DM Sans',
    role: 'body',
    axes: { tone: 0.3, era: 0.6, voice: 0.2, warmth: 0.25 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/DM+Sans',
    css: ['https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['DM Serif Display', 'Playfair Display'],
  },
  {
    family: 'Fira Sans',
    role: 'body',
    axes: { tone: 0.25, era: 0.5, voice: 0.2, warmth: 0.35 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Fira+Sans',
    css: ['https://fonts.googleapis.com/css2?family=Fira+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Playfair Display', 'Young Serif'],
  },
  {
    family: 'General Sans',
    role: 'body',
    axes: { tone: 0.3, era: 0.7, voice: 0.2, warmth: 0.2 },
    source: 'fontshare',
    license: 'ITF FFL',
    url: 'https://www.fontshare.com/fonts/general-sans',
    css: ['https://api.fontshare.com/v2/css?f[]=general-sans@400,401,700,701&display=swap'],
    companions: ['Clash Display', 'Zodiak'],
  },
  {
    family: 'Geist',
    role: 'body',
    axes: { tone: 0.25, era: 0.85, voice: 0.15, warmth: 0.1 },
    source: 'independent',
    license: 'OFL',
    url: 'https://vercel.com/font',
    css: ['https://cdn.jsdelivr.net/fontsource/css/geist@latest/index.css', 'https://cdn.jsdelivr.net/fontsource/css/geist@latest/700.css'],
    companions: ['Space Grotesk', 'Unbounded'],
  },
  {
    family: 'Hanken Grotesk',
    role: 'body',
    axes: { tone: 0.3, era: 0.7, voice: 0.25, warmth: 0.2 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Hanken+Grotesk',
    css: ['https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Space Grotesk', 'Fraunces'],
  },
  {
    family: 'Inter',
    role: 'body',
    axes: { tone: 0.3, era: 0.65, voice: 0.1, warmth: 0.2 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Inter',
    css: ['https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Archivo', 'Fraunces', 'Anton'],
  },
  {
    family: 'Karla',
    role: 'body',
    axes: { tone: 0.35, era: 0.6, voice: 0.2, warmth: 0.35 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Karla',
    css: ['https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Libre Caslon Display', 'Young Serif'],
  },
  {
    family: 'Lexend',
    role: 'body',
    axes: { tone: 0.25, era: 0.7, voice: 0.15, warmth: 0.15 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Lexend',
    css: ['https://fonts.googleapis.com/css2?family=Lexend:wght@400;700&display=swap'],
    companions: ['Space Grotesk', 'Manrope'],
  },
  {
    family: 'Literata',
    role: 'body',
    axes: { tone: 0.3, era: 0.35, voice: 0.3, warmth: 0.5 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Literata',
    css: ['https://fonts.googleapis.com/css2?family=Literata:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Playfair Display', 'Instrument Serif'],
  },
  {
    family: 'Lora',
    role: 'body',
    axes: { tone: 0.3, era: 0.3, voice: 0.3, warmth: 0.5 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Lora',
    css: ['https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Caveat', 'DM Serif Display'],
  },
  {
    family: 'Mulish',
    role: 'body',
    axes: { tone: 0.35, era: 0.6, voice: 0.2, warmth: 0.3 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Mulish',
    css: ['https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Fraunces', 'Young Serif'],
  },
  {
    family: 'Nunito Sans',
    role: 'body',
    axes: { tone: 0.55, era: 0.55, voice: 0.35, warmth: 0.5 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Nunito+Sans',
    css: ['https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Fredoka', 'Lobster'],
  },
  {
    family: 'Public Sans',
    role: 'body',
    axes: { tone: 0.2, era: 0.55, voice: 0.15, warmth: 0.2 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Public+Sans',
    css: ['https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Libre Caslon Display', 'Archivo'],
  },
  {
    family: 'Satoshi',
    role: 'body',
    axes: { tone: 0.35, era: 0.8, voice: 0.25, warmth: 0.15 },
    source: 'fontshare',
    license: 'ITF FFL',
    url: 'https://www.fontshare.com/fonts/satoshi',
    css: ['https://api.fontshare.com/v2/css?f[]=satoshi@400,401,700,701&display=swap'],
    companions: ['Clash Display', 'Zodiak'],
  },
  {
    family: 'Source Sans 3',
    role: 'body',
    axes: { tone: 0.2, era: 0.4, voice: 0.15, warmth: 0.55 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Source+Sans+3',
    css: ['https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Playfair Display', 'EB Garamond', 'Cormorant Garamond'],
  },
  {
    family: 'Spline Sans',
    role: 'body',
    axes: { tone: 0.4, era: 0.8, voice: 0.25, warmth: 0.2 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Spline+Sans',
    css: ['https://fonts.googleapis.com/css2?family=Spline+Sans:wght@400;700&display=swap'],
    companions: ['Unbounded', 'Space Grotesk'],
  },
  {
    family: 'Urbanist',
    role: 'body',
    axes: { tone: 0.4, era: 0.75, voice: 0.2, warmth: 0.15 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Urbanist',
    css: ['https://fonts.googleapis.com/css2?family=Urbanist:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Outfit', 'Poppins'],
  },
  {
    family: 'Work Sans',
    role: 'body',
    axes: { tone: 0.3, era: 0.55, voice: 0.15, warmth: 0.3 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Work+Sans',
    css: ['https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Fraunces', 'Cormorant Garamond', 'Anton'],
  },
  {
    family: 'Zilla Slab',
    role: 'body',
    axes: { tone: 0.3, era: 0.4, voice: 0.5, warmth: 0.45 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Zilla+Slab',
    css: ['https://fonts.googleapis.com/css2?family=Zilla+Slab:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Manrope', 'Libre Caslon Display'],
  },

  // ---------------------------------------------------------------------
  // mono
  // ---------------------------------------------------------------------
  {
    family: 'Fragment Mono',
    role: 'mono',
    axes: { tone: 0.3, era: 0.6, voice: 0.3, warmth: 0.45 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Fragment+Mono',
    css: ['https://fonts.googleapis.com/css2?family=Fragment+Mono:ital@0;1&display=swap'],
    companions: ['Inter', 'Literata'],
  },
  {
    family: 'Geist Mono',
    role: 'mono',
    axes: { tone: 0.2, era: 0.85, voice: 0.2, warmth: 0.1 },
    source: 'independent',
    license: 'OFL',
    url: 'https://vercel.com/font',
    css: ['https://cdn.jsdelivr.net/fontsource/css/geist-mono@latest/index.css', 'https://cdn.jsdelivr.net/fontsource/css/geist-mono@latest/700.css'],
    companions: ['Geist', 'Space Grotesk'],
  },
  {
    family: 'IBM Plex Mono',
    role: 'mono',
    axes: { tone: 0.15, era: 0.55, voice: 0.25, warmth: 0.15 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/IBM+Plex+Mono',
    css: ['https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Public Sans', 'Archivo'],
  },
  {
    family: 'JetBrains Mono',
    role: 'mono',
    axes: { tone: 0.2, era: 0.7, voice: 0.25, warmth: 0.15 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/JetBrains+Mono',
    css: ['https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Inter', 'Archivo'],
  },
  {
    family: 'Red Hat Mono',
    role: 'mono',
    axes: { tone: 0.2, era: 0.6, voice: 0.2, warmth: 0.2 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Red+Hat+Mono',
    css: ['https://fonts.googleapis.com/css2?family=Red+Hat+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Hanken Grotesk', 'DM Sans'],
  },
  {
    family: 'Roboto Mono',
    role: 'mono',
    axes: { tone: 0.15, era: 0.45, voice: 0.2, warmth: 0.1 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Roboto+Mono',
    css: ['https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Lexend', 'Karla'],
  },
  {
    family: 'Space Mono',
    role: 'mono',
    axes: { tone: 0.4, era: 0.7, voice: 0.4, warmth: 0.3 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Space+Mono',
    css: ['https://fonts.googleapis.com/css2?family=Space+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Space Grotesk', 'Unbounded'],
  },
  {
    family: 'Victor Mono',
    role: 'mono',
    axes: { tone: 0.45, era: 0.55, voice: 0.3, warmth: 0.55 },
    source: 'google',
    license: 'OFL',
    url: 'https://fonts.google.com/specimen/Victor+Mono',
    css: ['https://fonts.googleapis.com/css2?family=Victor+Mono:ital,wght@0,400;0,700;1,400;1,700&display=swap'],
    companions: ['Literata', 'Lora'],
  },
];
